import { Check, X } from "lucide-react";
import { CtaLink } from "./ui";

const ROWS = [["Monthly membership fee", "$0", "$149/mo"], ["Every 4th month free", true, false], ["Same price at every dose", true, false], ["Doctor visit & prescription included", true, true], ["Free 1-2 day shipping", true, false], ["Unlimited doctor consults", true, false], ["24/7 human support", true, false], ["Home injection kit included", true, false], ["Cancel anytime", true, true]] as const;
function Mark({ value, good }: { value: boolean | string; good?: boolean }) { if (typeof value === "string") return <strong className={good ? "is-good" : "is-bad"}>{value}</strong>; return value ? <Check className="is-check" aria-label="Included" /> : <X className="is-x" aria-label="Not included" />; }

export function Comparison() {
  return <section className="m4-section m4-compare" data-track-section="compare"><div className="m4-container m4-container--narrow"><header className="m4-section-head"><p className="m4-eyebrow">Compare InstaRx vs. the rest</p><h2>Why pay more for less?</h2><p>InstaRx doesn&apos;t just cost less. It delivers more: more care, more flexibility, and every 4th month free. See how it stacks up:</p></header><div className="m4-table" role="table" aria-label="InstaRx plan comparison"><div className="m4-table__head" role="row"><span role="columnheader" aria-label="Feature" /><strong role="columnheader">InstaRx<em>Lowest Price!</em></strong><strong role="columnheader">Others</strong></div>{ROWS.map(([label, ours, others]) => <div className="m4-table__row" role="row" key={label}><span role="rowheader">{label}</span><span role="cell"><Mark value={ours} good /></span><span role="cell"><Mark value={others} /></span></div>)}</div><p className="m4-compare__note">Comparison based on publicly available pricing and plan details of typical telehealth GLP-1 programs as of September 2026. Details may have changed. InstaRx is not affiliated with any other provider.</p><CtaLink location="compare" className="m4-btn">See if You Qualify</CtaLink></div></section>;
}
