import Image from "next/image";
import Link from "next/link";

const LINKS = [["Privacy Policy", "/policies/privacy-policy"], ["Terms & Conditions", "/policies/terms-and-conditions"], ["Telehealth Consent", "/policies/telehealth-consent"], ["Refund Policy", "/policies/refund-policy"], ["Safety Information", "/policies/safety"]] as const;

export function Footer() {
  return <footer className="m4-footer"><div className="m4-container"><div className="m4-footer__top"><div><Image src="/logos/instarx-logo-inverse.webp" alt="InstaRx" width={180} height={55} loading="lazy" /><p>Doctor-prescribed care, delivered.</p></div><div><strong>Contact us</strong><a href="mailto:support@instarx.com">support@instarx.com</a><a href="tel:+18666738730">(866) 673-8730</a></div><Image src="/images/badges/legitscript.svg" alt="LegitScript Certified" width={82} height={82} loading="lazy" /></div><nav className="m4-footer__links" aria-label="Legal links">{LINKS.map(([label, href]) => <Link href={href} key={href}>{label}</Link>)}</nav><div className="m4-footer__legal" id="offer-terms"><p>*Promotional offer. &quot;Every 4th month free&quot; pricing is applied as a 25% discount on a 4-month subscription, equal in value to one month at the standard monthly price. Customers are billed once every four months at the discounted rate; the discount is applied automatically at checkout and at each renewal. It does not constitute a separate free product, shipment, or billing period. Subscription renews automatically every four months at the then-current discounted rate unless canceled before the renewal date. Medication is prescribed at the sole discretion of a licensed healthcare provider after a medical intake and is not guaranteed; if you are not approved, you will not be charged. Offer available to new and eligible returning patients. Pricing subject to change. No cash value. Not combinable with other offers. This offer does not guarantee treatment outcomes.</p><p>Compounded medications are prepared by licensed U.S. pharmacies and are not FDA-approved; the FDA has not evaluated them for safety, efficacy, or quality. Results vary and depend on adherence, provider guidance, and lifestyle changes. Weight-loss figures reflect published clinical trials of the active ingredients and are not a guarantee of individual results.</p></div><div className="m4-footer__bottom"><span>© 2026 InstaRx. All rights reserved.</span><span>Secure &amp; HIPAA compliant</span></div></div></footer>;
}

