import Image from "next/image";
import { Check, Gift, Heart, ShieldCheck, Sparkles, Stethoscope } from "lucide-react";
import type { Offer, OfferItem } from "./types";
import { FreeLink, Price } from "./display";
import { CtaLink } from "./ui";

function PlanCard({ item, featured }: { item: OfferItem; featured?: boolean }) {
  const sema = ["No membership fees, ever", "Doctor visit & prescription included", "Same price at every dose", "Free 1-2 day temperature-controlled shipping", "Unlimited doctor consults & 24/7 support"];
  const tirz = ["Targets 2 hunger pathways (GIP + GLP-1)", "Highest average weight loss in its class", "Rated #1 for speed & results"];
  return <article className={`m4-plan ${featured ? "m4-plan--featured" : ""}`}><span className="m4-plan__badge">{featured ? "#1 rated for speed & results" : "Most affordable"}</span><div className="m4-plan__intro"><h3>{item.name}</h3><span>Compounded {featured ? "GLP-1 + GIP" : "GLP-1"} Injection</span><p>{featured ? "Our most powerful dual-action formula for greater, faster results." : "The reliable, affordable path to quiet cravings and steady weight loss."}</p></div><div className="m4-plan__offer"><Gift /><span>Commit to 4 Months<strong>&amp; Get EVERY 4TH MONTH <FreeLink /></strong></span></div><div className="m4-plan__price"><Image src={featured ? "/lose-weight/instarx-tirzepatide-v2.webp" : "/lose-weight/instarx-semaglutide-v2.webp"} alt={`${item.name} medication vial`} width={120} height={150} loading="lazy" /><div><p>Starting at</p><strong><Price value={item.effectiveMonthly} /><small>/mo</small></strong><span><s><Price value={item.retailMonthly} />/mo</s> month-to-month</span></div></div><ul className="m4-plan__list">{featured && <li className="m4-plan__lead">Everything in Semaglutide, plus:</li>}{(featured ? tirz : sema).map((feature) => <li key={feature}><Check /> {feature}</li>)}</ul><p className="m4-plan__saving"><Gift /> Save <Price value={item.savings} /> Every 4th Month<a href="#offer-terms">*</a> — FOREVER</p><CtaLink location="plans" treatment={item.treatment} className={`m4-btn ${featured ? "m4-btn--green" : ""}`}>Claim My FREE Month — {item.name}</CtaLink><small><Price value={item.planTotal} /> billed every 4 months · <s><Price value={item.strikePlanTotal} /></s> regular total · covers 4 months of medication</small></article>;
}

export function Plans({ offer }: { offer: Offer }) {
  return <section className="m4-section m4-plans" id="plans" data-track-section="plans"><div className="m4-container"><header className="m4-section-head"><p className="m4-eyebrow">Price-lock guarantee</p><h2>Every 4th Month is <FreeLink /> — <em>FOREVER</em></h2><p>Choose your medication. Commit to 4 months, pay for 3. Stay with us and we&apos;ll cover every 4th month, forever. Same price at every dose. Zero hidden fees.</p></header><div className="m4-plans__grid"><PlanCard item={offer.sema} /><PlanCard item={offer.tirz} featured /></div><div className="m4-includes"><p>Every plan includes</p><div><span><Stethoscope />Free dosage increases</span><span><Sparkles />Treatment changes anytime</span><span><Heart />Unlimited doctor consults</span><span><ShieldCheck />Home injection kit included</span></div><small>Free expedited shipping · 24/7 customer support · HSA/FSA eligible</small></div></div></section>;
}
