import type { Metadata } from "next";
import PolicyLayout from "../../../components/PolicyLayout";

export const metadata: Metadata = {
  title: "Third Party Partners",
  description: "A list of InstaRx third-party partners and affiliated companies.",
};

const partners = [
  "21st Century Insurance",
  "2insure4less",
  "A&B Insurance and Financial",
  "AAA Insurance Co.",
  "AABCO",
  "ABCLeads",
  "Abrazo Health",
  "ABS Healthcare",
  "ACA Express",
  "Acceptance",
  "Access Insurance",
  "AccordantMedia",
  "Accuquote",
  "Acordia",
  "Acquisition Tech",
  "Acquisition Technologies",
  "Ad Heavens – ADH",
  "Admaric",
  "Admediary",
  "Admiral Life",
  "Adrea Rubin",
  "ADT",
  "ADT Solar",
  "Advantra",
  "Advise Insurance",
  "Advocate Health",
  "Advocacy Center",
  "Advocate My Insurance",
  "Advocator Group",
  "Aegis First",
  "Aegis Security",
  "Aegon US Holding Corp.",
  "Aetna",
  "Affinity Health Plan",
  "Affirmative",
  "AFLAC",
  "AGA",
  "AgedLeadStore.com",
  "Agent Insider",
  "AgentCubed Marketplace",
  "Agentra Healthcare",
  "AHCP",
  "AHG Insurance",
  "AHH",
  "AHIA",
  "AHIX",
  "AIG",
  "AIG Direct",
  "AIO",
  "AIP",
  "AIS",
  "AIU",
  "AIU Insurance",
  "Alfa Insurance",
  "Aliera Healthcare",
  "All Digital Promotions",
  "All Nation",
  "All Risk",
  "All Web Leads",
  "Allegiant Group",
  "Alliance & Associates",
  "Alliance 321",
  "Alliance Insurance",
  "Alliance National Health",
  "Allianz",
  "Allied",
  "Allied Health",
  "Allied Insurance",
  "Allied Insurance Partners",
  "Allied Insurance Partners (view list)",
  "Allina Health",
  "Allstarz",
  "AllState",
  "Allstate County Mutual",
  "Allstate Indemnity",
  "Allstate Insurance",
  "AllWebLeads",
  "Alphatech Resource Holdings s.r.o.",
  "America Direct",
  "America's Health Advisors",
  "America's Trust, Inc.",
  "American",
  "American Alliance",
  "American Automobile Insurance",
  "American Banks",
  "American Benefits Group",
  "American Casualty",
  "American Continental",
  "American Deposit Insurance",
  "American Direct Business Insurance",
  "American Economy",
  "American Empire Insurance",
  "American Family",
  "American Family Insurance",
  "American Family Mutual",
  "American Fidelity Corp.",
  "American Financial",
  "American General",
  "American Health Plans",
  "American Health Underwriters",
  "American Home Assurance",
  "American Income Life Insurance Company",
  "American Insurance",
  "American Insurance Agencies",
  "American Insurance Agencies Direct Inc.",
  "American Insurance Organization",
  "American Insurance Organization, LLC",
  "American International",
  "American International Ins",
  "American International Pacific",
  "American International South",
  "American Life & Health",
  "American Manufacturers",
  "American Mayflower Insurance",
  "American Motorists Insurance",
  "American National Insurance",
  "American National Insurance Co",
  "American Police Officers Alliance",
  "American National Property and Casualty",
  "American Premier",
  "American Premier Insurance",
  "American Protection Insurance",
  "American Reliable",
  "American Republic",
  "American Republic Insurance Co.",
  "American Savers Plan",
  "American Security Insurance Company",
  "American Select",
  "American Service Insurance Agency",
  "American Skyline Insurance Company",
  "American Spirit Insurance",
  "American Standard",
  "American Standard Insurance – OH",
  "American Standard Insurance – WI",
  "American States",
  "Americare Group",
  "Americare/American Enterprise",
  "Americas Health Brokers",
  "America's Health Care Plan",
  "Americas Health Group",
  "America's Insurance",
  "AmeriChoice",
  "Americo",
  "Amerigroup",
  "AmeriHealth",
  "Amerilife",
  "AmeriPlan",
  "Ameriprise",
  "Ameriprise Financial Group",
  "Ameriquote",
  "Amerisure",
  "Amica",
  "Amica Insurance",
  "Angelic Marketing Group",
  "Angelic Marketing Group, LLC",
  "ANPAC",
  "Answer Financial",
  "Anthem",
  "Anthem/BCBS",
  "AON",
  "Aon Corp.",
  "API",
  "Apliant",
  "Apollo Interactive, Inc.",
  "Aragon Advertising",
  "Arbella",
  "Arcamax Publishing",
  "Arcamax Senior Living Newsletter",
  "Ardent Health Services",
  "Arizona General",
  "Armed Forces Insurance",
  "Ascend Health Insurance",
  "Assigned Risk",
  "Associated Indemnity",
  "Associated Insurance Managers",
  "Assurance IQ, Inc.",
  "Assurant",
  "Assurant, Bankers Life and Casualty",
  "Assured Life",
  "Astonish",
  "Astoria Company",
  "Atlanta Casualty",
  "Atlanta Specialty",
  "Atlantic Blue Media",
  "Atlantic Health",
  "Atlantic Indemnity",
  "Atlantis",
  "Atomic Leads",
  "Audience Serv",
  "Austin Mutual",
  "Auto Club Insurance Company",
  "Auto Help Center",
  "Auto Insurance Guide",
  "Auto Owners",
  "Avendia Management",
  "Avenge Digital",
  "Aviva",
  "Avmed",
  "AvMed Inc.",
  "Avomark",
  "AXA Advisors",
  "AXA Insurance Group",
  "Badger Mutual",
  "Bankers & Shippers",
  "Banker's Fidelity",
  "Bankers Life and Casualty",
  "Bankrate",
  "Bankrate Insurance",
  "Bankrate, Inc.",
  "Banner Life",
  "Bantam Connect",
  "Bartleson Brokers",
  "Bayside",
  "BBRS Group",
  "BCBS",
  "BCBS of Florida",
  "BCBS of Michigan",
  "Beacon Leads, LLC",
  "Benefit Advisors",
  "Benefit Mall",
  "Benepath",
  "Best Agency USA",
  "BestQuotes",
  "BH Insurance Solutions, LLC",
  "Blue Choice",
  "Blue Cross",
  "Blue Cross – Anthem",
  "Blue Cross Blue Shield",
  "Blue Cross of South Carolina",
  "Blue Cross/Blue Shield Association Companies",
  "Blue Shield of California",
  "Blue Wing Ads",
  "BlueCross/Blue Sheild Association Companies",
  "BMP Insurance",
  "Bold Media Group",
  "Bolt",
  "Bonneville",
  "Boost",
  "Boost Health Insurance",
  "Boost Health Insurance Senior Living Newsletter Powered by Arcamax",
  "Boost Marketing",
  "Boost Marketing, Inc.",
  "Boston Old Colony",
  "Bravo Health",
  "Brighter HealthCare Senior Protection, LLC",
  "Bright Health Plan",
  "Brightway",
  "Broadbase Media",
  "Brooke Franchise Corporation",
  "Brooke Insurance",
  "Brookstone Financial",
  "BRXTN Digital Media",
  "Btel",
  "Btel Communications",
  "Budget Family Insurance",
  "Builders",
  "c0aster",
  "Cal Farm Insurance",
  "California Casualty",
  "California State Automobile Association",
  "Call Blade",
  "Call Center Partnerships",
  "Call Lead Solutions",
  "Call Trader",
  "Call Trader LLC",
  "Call4SeniorSavings.com",
  "Cambia",
  "Camden",
  "CAN",
  "CancerInsurance.com",
  "Candid Maven",
  "Capital Choice",
  "Capital District Physicians Health Plan",
  "Capital Health Insurance of America",
  "Care Entrée",
  "CareMore",
  "Caresource",
  "CareZone",
  "Carezone Inc.",
  "Carle Clinic Association",
  "Cascade National Ins",
  "Casualty Assurance",
  "Catholic Financial Life",
  "CDPHP",
  "CEGE",
  "Cege Media",
  "Celtic Insurance",
  "Centene",
  "Centene Corp.",
  "Centennial",
  "Charter Oak",
  "Chase Insurance Group",
  "Cherry Blitz",
  "Chesapeake",
  "Chicago Insurance",
  "Choice Direct",
  "Choice Insurance",
  "Christian Fidelity",
  "Chubb",
  "Church Mutual",
  "Cigna",
  "Cigna, Coventry, Fortis",
  "Citigroup",
  "Citirex",
  "Citizens",
  "Citizens Disability",
  "Claim Your Benefits",
  "Clarendon American Insurance",
  "Clarendon National Insurance",
  "Clean Energy Concepts",
  "Clear One",
  "Clearlink",
  "Cloverleaf",
  "CMG Solutions",
  "CNA Insurance",
  "CO Farm Bureau",
  "Colby Direct",
  "Colonial",
  "Colonial Insurance",
  "Colonial Penn",
  "Combined",
  "Commercial Marketing Group",
  "Commercial Union",
  "CommercialInsurance.net",
  "Commonwealth",
  "Communicating for America",
  "Community Care",
  "CommunityCare",
  "Compare Insurance Quotes",
  "Compare.com",
  "CompareInsuranceQuotes",
  "Comparison Market",
  "Complete Home Services",
  "Connect Insurance Brands",
  "Connect One Health",
  "Connect Rite Bpo",
  "ConnectiCare",
  "Conseco Life",
  "Consumer Council",
  "Consumer United",
  "Contactability",
  "Continental Casualty",
  "Continental Divide Insurance",
  "Continental Insurance",
  "Continental Life",
  "Conventry",
  "Corner Shop Media",
  "Cotton States Insurance",
  "Cottonwood",
  "Country Companies",
  "Country Financial",
  "Country Insurance and Financial Services",
  "Countrywide Insurance",
  "Coventry",
  "Coventry Health Care",
  "Coverage One",
  "Coverage One Insurance",
  "Coverage One Insurance Group LLC",
  "Coverance Insurance Solutions, Inc.",
  "Coverdell",
  "CoverHound",
  "Covida",
  "Creative Emarketing",
  "Credit Union",
  "Criterion",
  "Crosspointe Insurance Advisors",
  "CS Marketing",
  "CSE",
  "CSE Insurance Group",
  "CUNA Mutual Group",
  "Dairyland",
  "Dairyland County Mutual Co of TX",
  "Dairyland Insurance",
  "Dapper Health Agency",
  "Datalot",
  "DataMax",
  "Datwerx",
  "Dean Health",
  "Deerbrook",
  "Delphi Financial",
  "DentalInsurance.com",
  "Depositors Emcasc",
  "Diablo Media",
  "Digiline Media",
  "Digital DBA",
  "Digital Market Media",
  "Digital Thrive",
  "Direct Auto",
  "Direct General",
  "Direct Property & Casualty",
  "Direct Web Advertising",
  "Disability Advisor",
  "Discount Insurance Quotes",
  "DiscoverBPO",
  "Dixie",
  "Dobak Holdings LLC",
  "Doc Auto Insurance",
  "DoublePositive",
  "Drips",
  "Drobu",
  "DTRIC",
  "Eagle Health",
  "eAmerifamily",
  "East Coast Health Insurance",
  "Ebco General",
  "Economy Fire & Casualty",
  "Economy Preferred",
  "Efinancial",
  "eHealth",
  "eHealth Insurance",
  "eHealth Insurance Services",
  "eHealthInsurance Services",
  "eHealthInsurance Services, Inc.",
  "EHG Insurance",
  "Elderplan",
  "Electric",
  "Electric Insurance",
  "Elephant",
  "eMarketing Media Group",
  "EmblemHealth",
  "EMC",
  "Empire",
  "Employers Fire",
  "Empower Brokerage",
  "Encompass",
  "Energy Alliance",
  "Enrollment Services Inc.",
  "Ensure",
  "Ensurem",
  "EPath",
  "EPCVIP",
  "EPIQ",
  "Equita Group",
  "Equita Group Final Expense Services",
  "Equitable Life",
  "Erie Insurance Company",
  "Erie Insurance Exchange",
  "Erie Insurance Group",
  "Erie Insurance Property and Casualty",
  "Esurance",
  "e-Telequote",
  "e-TeleQuote Insurance",
  "e-TeleQuote Insurance, Inc.",
  "Everest Financial & Insurance Services",
  "Every Choice Insurance",
  "Exact Match Media",
  "Excel Impact",
  "Excel Impact, LLC",
  "Excelium Group",
  "Excella Benefits, Inc.",
  "Excellus",
  "Explorer",
  "Facility",
  "Fallon Community Health Plan",
  "Family First Insurance Advisors",
  "Family Life",
  "Family/Rural",
  "Farm and Ranch",
  "Farm Bureau",
  "Farm Bureau/Farm",
  "Farmers Insurance",
  "Farmers Insurance Exchange",
  "Farmers TX County Mutual",
  "Farmers Union",
  "Farmland",
  "Federal",
  "Federated",
  "Federated American",
  "Federated Group",
  "Festive Health",
  "Fidelis",
  "Fidelity and Guaranty Life",
  "Fidelity Insurance Company",
  "Fidelity Investments Life",
  "Fidelity Life",
  "Fidelity National",
  "Fidelity Security Life",
  "Field of Leads Ltd.",
  "Fields of Leads",
  "Final Expense Assistant",
  "FinanceBox.com",
  "Financial Indemnity",
  "Fiorella Insurance",
  "Fiorella Insurance Agency",
  "Fire and Casualty Insurance Co of CT",
  "Firemans Fund",
  "Fireman's Fund",
  "First Acceptance Insurance",
  "First American",
  "First Choice Health",
  "First Family Insurance",
  "First Family Insurance Advisors",
  "First Financial",
  "First General",
  "First National",
  "First Preferred Insurance",
  "Flexquote",
  "Flex Rates",
  "Florida Blue",
  "Flyhigh",
  "Ford Motor Credit",
  "Forefront Insurance",
  "Foremost",
  "Foresters",
  "Forethought",
  "Formza",
  "Formza, LLC",
  "Fortegra",
  "Fortegra Insurance",
  "Fortegra Personal Insurance Agency",
  "Fortis",
  "Franklin",
  "Freedom health",
  "Freeway Insurance",
  "Fresh Leads",
  "Fuego Leads, LLC.",
  "Gainsco",
  "Gaurantee Trust Life",
  "Geber Life",
  "GEICO",
  "Geico Casualty",
  "Geico General Insurance",
  "Geico Indemnity",
  "Geisinger",
  "Geisinger Insurance",
  "Generation Life",
  "Generation Life Insurance",
  "Genworth",
  "Genworth Financial",
  "Gerber",
  "Gerber Life",
  "Get My Life Insured",
  "Get Seen Media",
  "GetAuto",
  "GetInsured",
  "GetMeHealthCare.com",
  "GHI",
  "GigUp",
  "Globalsky BPO",
  "Globe Life Insurance Company",
  "Globe Life Insurance Company of New York",
  "GMAC Insurance",
  "GMAC/NGIC",
  "Go Direct Lead Generation, LLC",
  "GoDirect Leads Generation",
  "GoHealth",
  "GoHealth.com",
  "GoHealth/Norvax",
  "GoHealthInsurance.com",
  "Goji",
  "Golden Rule",
  "Golden Rule Insurance",
  "Golden Rule Insurance Co.",
  "GoMediGap",
  "Government Employees",
  "Government Employees Insurance",
  "Government Personnel Mutual Life",
  "Grange",
  "GRE Harleysville H",
  "Great American",
  "Great Way",
  "Great West",
  "GreatAmerican",
  "Grey Peaks",
  "Grinnell Mutual",
  "Group Health Incorporated",
  "Guaranteed Benefits",
  "Guaranteed Health Options",
  "Guaranty National",
  "Guaranty National Insurance",
  "Guardian",
  "Guardian Healthcare",
  "Guardian Life",
  "Guide One",
  "Guide One Insurance",
  "Guide To Insure",
  "GuidePointe Solutions",
  "Guidestar Marketing Group LLC",
  "Halcyon",
  "Hanover",
  "Hanover Lloyd's Insurance Company",
  "HAP Health Alliance",
  "Happy Days",
  "Hartford",
  "Hartford Accident and Indemnity",
  "Hartford Casualty Insurance",
  "Hartford Fire & Casualty",
  "Hartford Fire Insurance",
  "Hartford Insurance Co of Illinois",
  "Hartford Insurance Co of the Southeast",
  "Hartford Life",
  "Hartford Omni",
  "Hartford Underwriters Insurance",
  "Harvard Commonwealth Health Plan",
  "Harvard Pilgrim",
  "HasTraffic",
  "HauteProspects",
  "Hawaii Medical Services Association",
  "Hawkeye Security",
  "HCC Insurance holdings",
  "Health & Life Advantage",
  "Health Advisors",
  "Health America",
  "Health and Life Associates",
  "Health and Life Plans of America",
  "Health Benefits Center",
  "Health Benefits Direct",
  "Health Benefits One",
  "Health Care Service Corp.",
  "Health Care Solutions",
  "Health Choice One",
  "Health Corp USA",
  "Health Dime",
  "Health eDeals",
  "Health Exchange Agency",
  "Healthguys Inc.",
  "Health Heritage Advisors",
  "Health I.Q.",
  "Health Insurance Advantage",
  "Health Insurance Advisors",
  "Health Insurance Alliance",
  "Health Insurance Alliance, LLC",
  "Health Insurance for Everyone",
  "Health Insurance Innovations",
  "Health Insurance of America",
  "Health Insurance Services",
  "Health IQ",
  "Health Markets",
  "Health Net",
  "Health Network",
  "Health Now New York Inc.",
  "Health Option One",
  "Health Partners of Philadelphia Inc.",
  "Health Plan One",
  "Health Plan Services",
  "Health Plans America",
  "Health Plans of America",
  "Health Plus",
  "Health Plus of America",
  "Health Pocket",
  "Health Sherpa",
  "Health Solutions One",
  "Health1nsurance.com",
  "Healthcare Advisors",
  "HealthCare Alternatives",
  "Healthcare Direct",
  "Healthcare Solutions Team",
  "Healthcare Solutions Direct, LLC.",
  "Healthcare, Inc.",
  "HealthCompare",
  "HealthCompare Insurance Services, Inc.",
  "HealthInsurance.net",
  "HealthIQ",
  "Health Line One",
  "Healthmarkets",
  "HealthMarkets / Insphere",
  "HealthMarkets Insphere",
  "HealthMarkets Insurance Agency",
  "HealthMarkets/Insphere",
  "HealthMatchup",
  "HealthNet",
  "HealthPartners",
  "HealthPlan Advisors",
  "HealthPlanMatchup",
  "HealthPlanOne",
  "HealthPlus of Michigan",
  "HealthPocket",
  "HealthQuoteInfo.com",
  "HealthShare America",
  "HealthShare American",
  "HealthSpire",
  "HealthSpring",
  "Healthworks",
  "Healthy Halo",
  "Heard and Smith",
  "Henry Ford Health System",
  "Heritage",
  "Heritage Health Advisors",
  "Heritage Life Insurance Company",
  "HHA",
  "HIA",
  "Highland Health Direct",
  "Highland Health Direct, LLC.",
  "Highmark",
  "Highmark BCBS",
  "HII",
  "HIP Health Plan",
  "HIP Insurance",
  "Hippo Insurance",
  "Hiscox",
  "HK Flavors Limited",
  "Hola Doctor",
  "HolaDoctor",
  "Home Bundles",
  "Home Insurance King",
  "Home Path",
  "Home Savings",
  "Homeinsurance.com",
  "Homeland Health",
  "Homeland Healthcare",
  "Hometown",
  "Hometown Quotes",
  "Horace Mann",
  "Horizon",
  "Hospital Services Association of NEPA",
  "HPO",
  "HSO",
  "HST",
  "HST Enrollment Center",
  "Humana",
  "HyperTarget",
  "Hypertarget Marketing",
  "IAB",
  "iCan Benefit",
  "iCan Benefit Group",
  "Ideal Concepts",
  "Ideal Concepts, Inc",
  "IDS",
  "IFA Auto Insurance",
  "IFA Insurance Company",
  "iFlourish Labs",
  "IGF Ins.",
  "IGF Insurance",
  "IHC",
  "IHC Group",
  "IHC Health Plans",
  "IIS Insurance",
  "IMO",
  "Independence Blue Cross",
  "Independent Carriers",
  "Independent Health Association",
  "Infinity Insurance",
  "Infinity National Insurance",
  "Infinity One",
  "Infinity Select Insurance",
  "Infinix Media",
  "ING",
  "ING US Life",
  "Innovation Direct Group",
  "Innovation Group of South Florida",
  "Inquire Media",
  "Inside Response",
  "Insphere",
  "Insphere Insurance Solutions",
  "InstaRx",
  "Insur. of Evanston",
  "InsuraMatch",
  "Insurance Care Direct",
  "Insurance Central",
  "Insurance Guide",
  "Insurance Insight",
  "Insurance Line One",
  "Insurance Management Associates",
  "Insurance Medics",
  "Insurance Services",
  "Insurance Solutions Direct",
  "Insurance.com",
  "InsuranceLeads.com",
  "InsuranceOnly",
  "InsuranceProz",
  "Insurancequotes",
  "InsuranceQuotes, Inc.",
  "insuranceQuotes.com",
  "Insure.com",
  "Insure Farm",
  "Insured Street",
  "InsureMe",
  "Insweb",
  "Integon",
  "Integrated Benefits",
  "IntelliQuote",
  "Inter Valley Health Plan",
  "Interstate",
  "Investors Life",
  "IPA Agents",
  "IPA Direct",
  "IPA Family",
  "iQuoteX",
  "iWebQuotes",
  "Jackson National Life",
  "JCG New Media",
  "JLS",
  "Job Hunt Helper",
  "John Deere",
  "John Hancock",
  "JRC Insurance Group",
  "Kaiser",
  "Kaiser Foundation Health Plan",
  "Kaiser Permanente",
  "Kaiser, Medicare Solutions",
  "Kallstar",
  "Kanopy",
  "Kanopy Insurance",
  "Keenan Associates",
  "Kelsey-Seybold",
  "Kemper",
  "Kemper Lloyds Insurance",
  "Kentucky Central",
  "Keystone",
  "Kind Health",
  "Knights of Columbus",
  "Koenig Quotes",
  "Komparison",
  "Landmark American Insurance",
  "Lands Health",
  "LBCOT Insurance",
  "Lead Foundations",
  "Lead Origins",
  "Leadco",
  "LeadEnvoy",
  "Leader General",
  "Leader Insurance",
  "Leader National",
  "Leader National Insurance",
  "Leader Preferred Insurance",
  "Leader Specialty Insurance",
  "Leadnomics",
  "League General",
  "Legal & General America",
  "Level One Health Group",
  "Liberty Health Plan",
  "Liberty Insurance Corp",
  "Liberty Mutual",
  "Liberty Mutual Fire Insurance",
  "Liberty Mutual Insurance",
  "Liberty Mutual Insurance Company",
  "Liberty National Life Insurance Company",
  "Liberty Northwest",
  "Liberty Northwest Insurance",
  "Life Grade Agency",
  "LifeInsuranceMatchup",
  "LifeLine Direct",
  "Life Matters",
  "LifeQuotes",
  "Lifetime Healthcare",
  "LifeWise Health Plan",
  "Lighthouse Insurance",
  "Lighthouse Insurance Group",
  "Lincoln Benefit Life",
  "Lincoln National",
  "Line East Leads",
  "ListenClear",
  "LoanBright",
  "Loan Resource Center",
  "Lockton Affinity Group",
  "Longevity Alliance",
  "Louisiana Health Services",
  "Loyal American",
  "LS Lead Generation",
  "LTC Financial Partners",
  "Lumbermens Mutual",
  "M Plan Inc.",
  "Managed Health Inc.",
  "MAPFRE",
  "Marathon",
  "Marchex",
  "Markel American",
  "Martin's Point",
  "Maryland Casualty",
  "Mass Mutual",
  "Mass Nexus",
  "Massachusetts Mutual",
  "MassNexus",
  "Match Media Group",
  "Matrix Direct",
  "Maxim Strategies",
  "Maxxlocal",
  "MedGapDirect",
  "Media Alpha",
  "Media Alpha Exchange",
  "Media Champs",
  "Medica",
  "Medical Card System Inc.",
  "Medical Mutual of Ohio",
  "Medicare Finder",
  "Medicare ME",
  "Medicare Providers",
  "Medicare Solutions",
  "MedicareAdvantage.com",
  "Medicare Rewards",
  "MedX Publishing",
  "MedicareProz",
  "Med Alert Pros",
  "MEGA Life and Health",
  "Mega/Midwest",
  "Mendota",
  "Merastar",
  "Mercury",
  "Mercy",
  "Metlife",
  "MetLife Auto and Home",
  "Metropolitan Co.",
  "Metropolitan Insurance Co.",
  "Mid Century Insurance",
  "Mid-Continent Casualty",
  "Middlesex Insurance",
  "Midland National",
  "Midland National Life",
  "Midwest Mutual",
  "Mid-West Ntl. Life",
  "Migo Insure",
  "Mikayla Data",
  "Millbank",
  "Millers Mutual",
  "Milwaukee General",
  "Milwaukee Guardian",
  "Milwaukee Mutual",
  "Minnehoma",
  "Minnesota Mutual",
  "Mississippi Insurance",
  "Missouri General",
  "MJ Direct",
  "MMI Group",
  "MMM Healthcare Inc.",
  "Modern Health, LLC",
  "Modern Woodmen of America",
  "Molina",
  "Molina Healthcare Inc.",
  "Mony Group",
  "Mortgage Protection Bureau",
  "Moss",
  "Moss Affiliate",
  "Moss Affiliate Marketing",
  "Motors",
  "Mountain Financial",
  "Mountain Laurel",
  "Mutual Insurance",
  "Mutual Of Enumclaw",
  "Mutual of New York",
  "Mutual of Omaha",
  "MVP",
  "MyHealthAngel.com",
  "My Home Helpers",
  "MyInsuranceExpert",
  "Nation Health Advisors",
  "National Alliance",
  "National Ben Franklin Insurance",
  "National Better Living Association",
  "National Brokerage",
  "National Brokers of America",
  "National Casualty",
  "National Police & Sheriffs Coalition PAC",
  "National Colonial",
  "National Continental",
  "National Continental Insurance",
  "National Disability",
  "National Family Assurance Group, Inc.",
  "National Fire Insurance Company of Hartford",
  "National General Insurance",
  "National Health Connect LLC",
  "National Health Connect, LLC",
  "National Health Hub",
  "National Health Hub LLC",
  "National Health Hub, LLC",
  "National Health Insurance",
  "National Health Plans dba Your Lowest Quote",
  "National Health Solutions",
  "National Healthcare Advisors",
  "NationalHomeProject",
  "National Income Life Insurance Company",
  "National Indemnity",
  "National Insurance",
  "National Merit",
  "National Surety Corp",
  "National Union Fire Insurance",
  "National Union Fire Insurance of LA",
  "National Union Fire Insurance of PA",
  "Nations Health Group Guide One Insurance",
  "Nations Insurance Solutions",
  "Nationwide",
  "Nationwide General Insurance",
  "Nationwide Health Advisors",
  "Nationwide Insurance Company",
  "Nationwide Mutual Fire Insurance",
  "Nationwide Mutual Insurance",
  "Nationwide Property and Casualty",
  "Nat'l Farmers Union",
  "Navy Mutual Aid Association",
  "Neighborhood Health Plan Inc.",
  "Neilson Financial Services",
  "Neo Ogilvy",
  "NetQuote",
  "New England Financial",
  "New Era",
  "NewStrata",
  "New York Life",
  "New York Life Insurance",
  "NewQuest",
  "Next Gen",
  "Next Wave Marketing",
  "Next Wave Marketing Strategies, Inc",
  "NextGen",
  "NextGen Leads",
  "NGIC",
  "NHA",
  "NMP Insurance Services, LLC / NameMyPremium",
  "Noridian Mutual Insurance Company",
  "North American",
  "North Pacific",
  "North Pointe",
  "North Shore",
  "Northern Capital",
  "Northern States",
  "Northland",
  "Northwest Medical",
  "Northwest Pacific",
  "Northwestern",
  "Northwestern Mutual",
  "Northwestern Mutual Life",
  "Northwestern Pacific Indemnity",
  "Norvax",
  "Norvax, LLC.",
  "NuHealth",
  "NuStar Insurance",
  "Offer Advisors",
  "Offer Strategy",
  "Offerweb",
  "Ohio Casualty",
  "Ohio National Life",
  "Ohio Security",
  "Old Mutual US Life",
  "Olympia",
  "Omaha",
  "Omni Indemnity",
  "Omni Insurance",
  "ONCOR Insurance Services",
  "One Touch Direct",
  "Onyx Digital Media",
  "Open Market Quotes",
  "Optimum HealthCare",
  "Oregon Mutual",
  "Orion Ins.",
  "Orion Insurance",
  "Oscar",
  "OSCAR Health",
  "Oscar Health Insurance",
  "Otis Production LLC",
  "Oxford",
  "Oxford Health Plans",
  "Oxford Insurance",
  "Oxford Marketing Partners",
  "Oxford Marketing Partners, LLC",
  "Pacific Benefits Group",
  "Pacific Benefits Group Northwest",
  "Pacific Indemnity",
  "Pacific Insurance",
  "Pacific Life",
  "Pacific Life and Annuity",
  "PacifiCare",
  "Pafco",
  "Pafco General Insurance",
  "Palmetto Senior Solutions",
  "Palms Health Group",
  "Paloverde",
  "Parasol Agents Network",
  "Parasol Leads",
  "Parasol Leads, Inc.",
  "Patriot General",
  "Patriot General Insurance",
  "Pay Per Call Market",
  "Peace of Mind Solutions",
  "Peak Performance",
  "Peak Property and Casualty Insurance",
  "Pemco",
  "PEMCO Insurance",
  "Penn America",
  "Penn Mutual",
  "Pennsylvania Natl",
  "Phoenix",
  "Phoenix Life",
  "Physicians Health Plan",
  "Physicians Life",
  "Physicians Mutual",
  "Physicians United Plan",
  "Pickett Group/TermLifeMatch",
  "Pier21 Media",
  "Ping Leads",
  "Pinnacle",
  "Pinnacle Publishers LLC",
  "Pinney Insurance Center, Inc.",
  "Pioneer Life",
  "Pivot",
  "Pivot Health",
  "PJP Agency",
  "PJP Health",
  "PJP Health Agency",
  "Platinum Leads",
  "Plymouth Rock",
  "PMIC",
  "Policy Scout",
  "PolicyFuel",
  "PolicyScout",
  "Power Source Marketing",
  "Practical Marketing",
  "Precise Health Insurance Advisors",
  "Precise Leads",
  "Precise Solutions Group",
  "Precursor Media",
  "Preferred Abstainers",
  "Preferred Care",
  "Preferred Mutual",
  "Premera Blue Cross",
  "Premier",
  "Premier Business Solutions",
  "Premier Disability",
  "Premier Health Solutions",
  "Premium Precision Marketing",
  "Presbyterian Health Plan",
  "Presbyterian Healthcare Services",
  "Presidio",
  "Presidio Interactive",
  "Presidio Interactive Corp",
  "Prestige",
  "Primary Health Care",
  "Prime Care",
  "Prime Care Health",
  "Primerica",
  "Principal",
  "Principal Financial",
  "Principal Life",
  "Priority Health",
  "Pristine Media Group",
  "Progressive",
  "Progressive Auto Pro",
  "Progressive Insurance",
  "Progressive Motorcycle",
  "Protective Casualty",
  "Protective Life",
  "Providence",
  "Providence Health Plan",
  "Provident",
  "Prudential",
  "Prudential Insurance Co.",
  "Prudential of America",
  "PURE",
  "Puritan Health",
  "Purple Dog Marketing LLC",
  "Pyramid Life",
  "Q3M Insurance Solutions",
  "Qatalyst",
  "QHS",
  "Qualilty Healthcare Solutions",
  "Quality",
  "Quality Healthcare Solutions",
  "Quality Healthcare Solutions, Inc.",
  "Quantum 3 Media LLC",
  "Quick Life Center, LLC",
  "QuickInsured",
  "QuickQuote",
  "QuinStreet",
  "Quote Engine",
  "Quote Selection",
  "Quote Selection Insurance Services, Inc",
  "Quote Velocity",
  "Quote Wizard",
  "QuoteStorm",
  "QuoteWhiz",
  "QuoteWhiz, LLC",
  "QuoteWizard",
  "Ramsey",
  "Ranger",
  "Rank Media",
  "Rank Media Agency",
  "RBC Liberty Insurance",
  "Real Results",
  "RedVentures",
  "Reel Media Ventures",
  "Regal",
  "Regence",
  "Reliance",
  "Reliance Insurance",
  "Reliance National Indemnity",
  "Reliance National Insurance",
  "Reliant",
  "ReliaQuote",
  "Renaissance Health Services Corp.",
  "Renew.com",
  "Renew.com Inc.",
  "Republic Indemnity",
  "Resource Marketing Corp.",
  "Response Insurance",
  "Revi Media",
  "ReviMedia",
  "RevPoint Media",
  "Rex Direct",
  "Ring Latino",
  "Ring Router",
  "Rockford Mutual",
  "Rodney D. Young",
  "Rogue E-Cigs",
  "RSA",
  "S.B. Fintech Ltd",
  "Safe Auto",
  "SAFECO",
  "Safeguard",
  "Safeway",
  "Safeway Insurance",
  "Safeway Insurance Co of AL",
  "Safeway Insurance Co of GA",
  "Safeway Insurance Co of LA",
  "Sagicor",
  "SalesRadix",
  "Savings Bank Life Insurance Company of Massachusetts (SBLI) Scan Health Plan",
  "SCMS",
  "Scott and White",
  "Sea West Insurance",
  "Seascape",
  "Seascape Health",
  "Seascape Life",
  "Secura",
  "Secure Horizons",
  "Secured Health",
  "Security Health Plan of Wisconsin Inc.",
  "Security Insurance",
  "Security Insurance Co of Hartford",
  "Security National",
  "Security National Insurance Co of FL",
  "Sedgwick James",
  "Select Quote",
  "Select Quote Senior",
  "SelectHealth",
  "Selective Healthcare",
  "SelectQuote Insurance Services",
  "SelectQuote Life",
  "SelectQuote Senior",
  "Senior Aid Helper",
  "Seniorcare USA",
  "Senior Health Advisors",
  "Senior Health Direct",
  "Senior Help Guide",
  "Senior Healthcare Direct",
  "Senior Life",
  "Senior Market",
  "Senior Market Advisors",
  "Senior Market Partners",
  "Senior Market Quotes",
  "Senior Market Sales",
  "SeniorQuote Insurance Services",
  "Sentara Health Management",
  "Sentinel Insurance",
  "Sentry",
  "Sentry Group",
  "Sentry Insurance a Mutual Company",
  "Sentry Insurance Company",
  "Sentry Insurance Group",
  "Shelter Insurance Co.",
  "Shelter Insurance Company",
  "Sierra Health Services",
  "Simple Health",
  "Simple Health Plans",
  "Simple Health Plans Inc.",
  "Simple Insurance",
  "Simple Insurance Leads",
  "Simpson Financial Group",
  "Singularity Media",
  "Skandia TIG Tita",
  "Smart Match Insurance Solutions",
  "Smart Relief Rx",
  "Smedley Insurance Group",
  "SolidQuote",
  "SolidQuote LLC",
  "SolidQuote, LLC",
  "Spectrum Direct",
  "Spectrum Health",
  "Spring EQ",
  "Spring Health Plans",
  "Spring Insurance",
  "Spring Insurance Solutions",
  "Spring Venture",
  "Spring Venture Group",
  "SS Telemarketing",
  "St. Paul",
  "St. Paul Companies",
  "St. Paul Fire and Marine",
  "St. Paul Insurance",
  "Stancorp Financial",
  "Standard Fire Insurance Company",
  "Standard Guaranty",
  "Standard Life",
  "State and County Mutual Fire Insurance",
  "State Auto",
  "State Farm",
  "State Farm County",
  "State Farm Fire and Cas",
  "State Farm General",
  "State Farm Indemnity",
  "State Farm Insurance Co.",
  "State Farm Lloyds Tx",
  "State Farm Mutual Auto",
  "State Fund",
  "State Mutual",
  "State National",
  "State National Insurance",
  "Sterling",
  "Sterling Senior Health",
  "Stone Hill National",
  "StoneTapert Employee Benefits",
  "Strategy Bay",
  "SubjectWell",
  "SummaCare",
  "Summit Health",
  "Sun Coast",
  "Sun Life Assurance Company",
  "Sunrise Health",
  "Sun Power",
  "Sunrun",
  "Superior American Insurance",
  "Superior Global Marketing Inc.",
  "Superior Guaranty Insurance",
  "Superior Home",
  "Superior Insurance",
  "Support First",
  "Sure Health Plans",
  "Sureco",
  "Sureco Legacy Insurance Services, Inc",
  "Sutter",
  "SVG",
  "Swiss Re",
  "Tallac Media",
  "Tech Insurance",
  "TexanPlus",
  "The Ahbe Group",
  "The Benefit Depot",
  "The Benefit Link",
  "The Complete Lead",
  "The Credo Group",
  "The General",
  "The Hartford",
  "The Insurance Center",
  "The Lead Company",
  "The Medicare Assistant",
  "The Senior Resource Group",
  "The-Solar-Project.com",
  "The Zebra",
  "Three Rivers Holdings",
  "Thrivent Financial for Lutherans",
  "TIAA-CREF",
  "Tiburon Insurance Services",
  "TICO Insurance",
  "TIG Countrywide Insurance",
  "Titan",
  "Titan Indemnity",
  "Tobias & Associates",
  "Torchlight",
  "Torchlight Technology",
  "Torchmark",
  "Total",
  "Touchstone",
  "Tower",
  "Towers Watson dba OneExchange",
  "TPG Direct",
  "TradeMarc Global, LLC",
  "Traders Insurance",
  "Traffic Panda",
  "Transamerica",
  "TZ Insurance Solutions LLC",
  "TruBridge, Inc.",
  "Travelers Indemnity",
  "Travelers Insurance",
  "Travelers Insurance Company",
  "Trinity Universal",
  "Triple-S Inc.",
  "TriState",
  "Tri-State Consumer",
  "Tri-State Consumer Insurance",
  "Tru Source",
  "TrueChoice Insurance Services",
  "TruSource Marketing",
  "Trust Hall",
  "Trusted Consumer Advisors",
  "Tryton",
  "TSC Insurance",
  "Tufts",
  "Tufts Associates HMO Inc.",
  "Tufts Health Plan",
  "Twentieth Century",
  "TWG",
  "Twin City Fire Insurance",
  "U S Financial",
  "Ucare",
  "UMA",
  "Underground Elephant",
  "Unicare",
  "Uniguard",
  "Union",
  "Unique Q2B",
  "United American Insurance Company",
  "United American/Farm and Ranch",
  "United Financial",
  "United Fire & Casual",
  "United Healthcare",
  "United Healthcare Advisors",
  "United Insurance",
  "United Insurance Group Agency, Inc.",
  "United Medicare",
  "United Medicare Advisors",
  "United of Omaha",
  "United Pacific Insurance",
  "United Security",
  "United Services Automobile Association",
  "United States Fideli",
  "UnitedHealthcare/UnitedHealthOne",
  "UnitedHealthOne",
  "Unitrin",
  "Unitrin Direct",
  "Unitrin Inc.",
  "Universal American",
  "Universal American Financial Corp.",
  "Universal Health Care",
  "Universal Underwriters Insurance",
  "University Health Care Inc.",
  "Unsure",
  "UnumProvident Corp.",
  "UPMC",
  "UPMC Health System",
  "US Benefit Solutions",
  "US Financial",
  "US Financial Life",
  "US Health Advisors",
  "US Health Group",
  "US Web Leads",
  "USA Benefits/Continental General",
  "USA Dental Club",
  "USAA",
  "USA Rate Center",
  "USF and G",
  "USF&G;",
  "USHEALTH Group",
  "USInsuranceOnline",
  "Utah Home and Fire",
  "Utica",
  "Vanguard Health Ventures",
  "Vantis Life",
  "Vasa North Atlantic",
  "Velapoint",
  "VelaPoint Personal Insurance",
  "Verified Insurance Lead",
  "Versible Connect",
  "Versus Media Group",
  "Verti Insurance",
  "Vertigen LLC",
  "Vigilant",
  "Viking",
  "Viking County Mutual Insurance",
  "Viking Insurance Co of WI",
  "VIMO",
  "Visiqua",
  "Vital One Health Plans Direct, LLC",
  "Vitalone",
  "Vitalone Health",
  "VitalOne Health Plans",
  "Viva Health",
  "Voxify",
  "Voxify LLC",
  "Washington National Life",
  "Wawaunesa",
  "Wax Digital Solutions",
  "We Speak",
  "WEA Inc.",
  "WebTec",
  "Wejo",
  "Wellcare",
  "WellCare Health Plans",
  "Wellington",
  "Wellness Plan of America",
  "WellPoint",
  "West American",
  "West Bend Mutual",
  "West Field",
  "West Plains",
  "Western & Southern Life",
  "Western and Southern Life",
  "Western Mutual",
  "Western National",
  "Westfield",
  "William Penn",
  "Windsor",
  "Windsor Insurance",
  "Windstar",
  "Wisconsin Mutual",
  "Woodlands Financial Group",
  "World Insurance",
  "Worldwide",
  "WynnHealth",
  "XLHealth",
  "XLHealth.",
  "Yasha Marketing",
  "Yellow Key",
  "Yosemite",
  "Your Lowest Quote",
  "YourHealthCareQuotes.com",
  "Zander",
  "ZebraA1333",
  "Zenith Media",
  "Zoom Insurance",
  "ZQ Sales",
  "Zurich",
  "Zurich North America",
  "Zurich North America or other partners.",
];

export default function ThirdPartyPartnersPage() {
  return (
    <PolicyLayout>
      <h1 className="text-3xl font-bold mb-4">Third Party Partners</h1>
      <p className="text-gray-600 mb-8">
        The following is a list of third-party companies and partners that may receive or process personal data in
        connection with our Services. This list is subject to change.
      </p>
      <div className="columns-1 sm:columns-2 lg:columns-3 gap-6">
        {partners.map((partner, i) => (
          <p key={i} className="text-sm text-gray-700 mb-1 break-inside-avoid">
            {partner}
          </p>
        ))}
      </div>
    </PolicyLayout>
  );
}
